services:

  backend:
    image: rag-backend

    container_name: rag-backend

    ports:
      - "8000:8000"

    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db

  frontend:
    image: rag-frontend

    container_name: rag-frontend

    ports:
      - "8501:8501"

    environment:
      - API_BASE_URL=http://backend:8000

    depends_on:
      - backend